name: "Release"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v2.0.0
      - name: Test
        run: |
          helmfile --version
          helm version
          kubectl version --client
      - name: Deploy Helm chart
        run: |
          helmfile apply -f ./deployments/prod/helmfile.yaml

      - name: Publish Helm chart
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          chart_glob: '*.tgz'
          repo_name: ${{ env.REPOSITORY_NAME }}
          chart_file_glob: 'ml-batch-0.1.0.tgz'
